### ISSUE TITLE
CompleteDNS ERROR

### ISSUE THREAD

**Issue by qodirovhamidjon** [greycatz/CloudUnflare#1]
Input domain name
 Example: google.com
 >> example.com

 INFO: Checking example.com
   + 104.17.193.81 [CLOUDFLARENET]
   + 104.17.194.81 [CLOUDFLARENET]
 INFO: Subdomain enumeration progress [20/67]
 INFO: Subdomain enumeration progress [40/67]
 INFO: Subdomain enumeration progress [60/67]
 ERROR: CompleteDNS cannot login

**Comment by greycatz** [comment]
Hello @qodirovhamidjon 

Please read [documentation](https://github.com/greycatz/CloudUnflare/blob/master/README.md) first.

Thank you.
